### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by 0xC4N1** [0xC4N1/video2clipboard#1]
Depending on:
- [ ] Implement contextMenus.create WebExtension API method on android [#1363016](https://bugzilla.mozilla.org/show_bug.cgi?id=1363016)
- [ ] Implement contextMenus.onClicked WebExtension API event on android [#1363020](https://bugzilla.mozilla.org/show_bug.cgi?id=1363020)
- [ ] [tracking] ContextMenus API support for Android WebExtensions [#1269062](https://bugzilla.mozilla.org/show_bug.cgi?id=1269062)
